server:
  address: localhost
  port: 8088

spring:
  jpa:
    show_sql: true

    hibernate:
      ddl-auto: create-drop
      database-platform: org.hibernate.dialect.MariaDB103Dialect
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

    properties:
      hibernate:
        default_batch_fetch_size: 500
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

  datasource:
    url: jdbc:h2:mem:palette?useSSL=false&useLegacyDatetimeCode=false&characterEncoding=UTF-8
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG

springdoc:
  version: v1
