spring:
  profiles:
    active: prod

  jpa:
    show_sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect

    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500

  datasource:
    url: jdbc:mariadb://team-palette.csnwgfh536zs.ap-northeast-2.rds.amazonaws.com/palette?useSSL=false&useLegacyDatetimeCode=false&characterEncoding=UTF-8&useUnicode=true&allowMultiQueries=true
    driverClassName: org.mariadb.jdbc.Driver

logging:
  level:
    root: INFO

server:
  port: 8081
